# extends: ../tspconfig.yaml                    # Extend another config file
emit:                                         # Emitter name
  - "@azure-tools/typespec-python"
options:                                      # Emitter options
    "@azure-tools/typespec-python":
      "package-version": 1.0.0b1
      "package-name": arm-mgmt-chaos
#   <emitter-name>:
#    "<option-name>": "<option-value>"
# environment-variables:                        # Environment variables which can be used to interpolate emitter options
#   <variable-name>:
#     default: "<variable-default>"
# parameters:                                   # Parameters which can be used to interpolate emitter options
#   <param-name>:
#     default: "<param-default>"
# trace:                                        # Trace areas to enable tracing
#  - "<trace-name>"
# warn-as-error: true                           # Treat warnings as errors
# output-dir: "{project-root}/_generated"       # Configure the base output directory for all emitters